### ISSUE TITLE
Issue with bridges missing from routing file

### ISSUE THREAD

**Issue by quickskape** [itinero/routing#98] opened 2017-05-04 13:56 UTC
I am trying to understand more about the available profiles used for routing cars.

I have an issue where my profile doesn't seem to be including a bridge.
I think the profile I have setup is missing something but I am having discovering what I am missing.
Can anyone suggest any links to documentation? or point me in the right direction?

Any help would be great thanks 👍

**Comment by xivk** [comment] 2017-05-04 14:46
Will try to help, a few questions:

Are you missing the road the bridge represents or the bridge meta data? Do you have a link to the bridge in OSM? Are you using the default profiles?

**Comment by quickskape** [comment] 2017-05-15 11:10
Thanks, I would really appreciate your input.

I appear to be missing the road the bridge represents, I have reverted to the default profile found: 
[https://github.com/itinero/vehicles/blob/master/car.lua](https://github.com/itinero/vehicles/blob/master/car.lua)

An Example start and end would be 
* Start: 50.413863, -4.326339
* End: 50.365951, -4.093641

One of the bridges I would expect to be used is: 

[http://www.openstreetmap.org/way/169351127 ](http://www.openstreetmap.org/way/169351127)

The route that is generated using Itinero is:

[http://bl.ocks.org/anonymous/raw/8eafed6d1ba04b7277ac5a8b63590c92/](http://bl.ocks.org/anonymous/raw/8eafed6d1ba04b7277ac5a8b63590c92/)

I would expect it to use something more simular too:
[https://www.google.co.uk/maps/dir/50.413863,-4.326339/50.365951,+-4.093641/@50.3986897,-4.2266347,12.75z/data=!4m6!4m5!1m0!1m3!2m2!1d-4.093641!2d50.365951](https://www.google.co.uk/maps/dir/50.413863,-4.326339/50.365951,+-4.093641/@50.3986897,-4.2266347,12.75z/data=!4m6!4m5!1m0!1m3!2m2!1d-4.093641!2d50.365951)

Any ideas what I could be doing incorrectly to get these results?

Thanks again.

**Comment by xivk** [comment] 2017-06-08 17:41
@quickskape This is probably due to a bug in Itinero, I will be releasing a new version soon fixing this.

I'll try to confirm that this is fixed in the next couple of days.

**Comment by quickskape** [comment] 2017-06-12 10:49
@xivk That's great, I will update to the new version as soon as it's available.

Thanks 👍

**Comment by xivk** [comment] 2017-06-13 18:19
Ok, tested and fixed:

http://geojson.io/#id=gist:anonymous/9942896206a31568beb6e1bb2994cbc4&map=12/50.3872/-4.2018

When releasing 1.1 this will be fine, the way things look now expect a release before the end of the week.

About the cause: basically it was a mistake I made implementing contraction with support for turn restrictions. In this case a shortcut that was supposed to be in the contracted graph wasn't there causing it to give incorrect and way longer routes than it should have.

**Closed by xivk** 2017-06-13 18:19 UTC
Labels: question

**Comment by quickskape** [comment] 2017-06-14 15:09
@xivk Thanks, that's great news.

That's good to hear, I look forward to the new release 👍 

That's interesting, so the shorter route wouldn't have been included, hence why the longer route was used?
Still trying to learn about how this all fits together. 
Thanks again for the extra information. 😄
