### ISSUE TITLE
Shapefile generation identifier issue

### ISSUE THREAD

**Issue by jbelien** [itinero/routing#136] opened 2017-11-02 11:04 UTC
In the Shapefile generated [here](http://files.itinero.tech/data/itinero/routerdbs/planet/europe/), there seems to be segments with `from_node`/`to_node` exact same identifier and same length.

From file generated on Tuesday 31/10/2017 :
- 144.228 segments with same identifiers
- Tagged as "track"
- Length = 205,544m.

**Comment by xivk** [comment] 2017-11-03 14:30
Still cannot reproduce this, would you be open to writing some code that check this on the files?

**Comment by jbelien** [comment] 2017-11-03 14:44
Of course :)
Here is the incriminated file : https://transfer.sh/OVcOd/belgium.a.shp.zip

**Comment by xivk** [comment] 2017-11-15 17:13
I can only find one entry in the above shapefile starting with vertex `from=844309` but it's to `to=844312`. Perhaps something else is going on?

When I open the shapefile everything looks normal.

**Comment by jbelien** [comment] 2017-11-18 16:09
I'm on holidays at the moment but I'll ask Philippe next week !
Totally possible that it is an issue with MapInfo that can't handle bug Shapefile ...

**Comment by xivk** [comment] 2018-01-12 12:25
Closing this one for now, feel free to reopen if you see fit @jbelien

**Closed by xivk** 2018-01-12 12:25 UTC
Labels: bug
